name: X5App
options:
  bundleIdPrefix: com.x5
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: 14.0
targets:
  X5App:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_NAME: "X5 App"
        PRODUCT_BUNDLE_IDENTIFIER: "com.x5.myapp"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        DEVELOPMENT_TEAM: "" # LEAVE EMPTY usually for manual signing or Codemagic handles it
        INFOPLIST_KEY_UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        INFOPLIST_KEY_UILaunchScreen: {}
        GENERATE_INFOPLIST_FILE: YES
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
