name: X5App
options:
  bundleIdPrefix: com.x5
  deploymentTarget:
    iOS: 15.0
targets:
  X5App:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_NAME: "X5 App"
        PRODUCT_BUNDLE_IDENTIFIER: "com.x5.myapp"
        CURRENT_PROJECT_VERSION: 5
        MARKETING_VERSION: 1.0.1
        DEVELOPMENT_TEAM: "F8LA8PC4U6"
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        INFOPLIST_KEY_CFBundleIconName: "AppIcon"
    info:
      path: Sources/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: "LaunchBackgroundColor"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
